### ISSUE TITLE
roundcube 1.1.4 does not work

### ISSUE THREAD

**Issue by achch** [RadioStudent/rcube-quota-notify#1]
php ver: 5.5.30

PHP Error: Failed to load plugin file /usr/local/www/apache24/data/rc/plugins/rcube-quota-notify/rcube-quota-notify.php in /usr/local/www/apache24/data/rc/program/lib/Roundcube/rcube_plugin_api.php on line 198 (POST /rc/?_task=mail&_action=refresh?_task=&_action=)

**Comment by borutmrak** [comment]
Rename the plugin folder to **quota_notify** (mv /usr/local/www/apache24/data/rc/plugins/rcube-quota-notify /usr/local/www/apache24/data/rc/plugins/quota_notify) and also use quota_notify instead of rcube-quota-notify as the plugin name in $plugins variable in the config, then it should work.

**Comment by achch** [comment]
Now renamed, so this error:
PHP Error: No plugin class quota_notify found in /usr/local/www/apache24/data/rc/plugins/quota_notify/quota_notify.php in /usr/local/www/apache24/data/rc/program/lib/Roundcube/rcube_plugin_api.php on line 191

**Comment by achch** [comment]
work! tnx
