### ISSUE TITLE
No plugin class quota_notify found (rc 1.1.4 php 5.5.30) 

### ISSUE THREAD

**Issue by achch** [RadioStudent/rcube-quota-notify#2]
PHP Error: No plugin class quota_notify found in /usr/local/www/apache24/data/rc/plugins/quota_notify/quota_notify.php in /usr/local/www/apache24/data/rc/program/lib/Roundcube/rcube_plugin_api.php on line 191

**Comment by borutmrak** [comment]
it seems I didn't commit the last change that was needed, I did it now. Please pull the last commit in the repo, it should fix your problem.
